=== VadimStrapko/Java/Internet_programming_technology/laba3/files/validation.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://msiter.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Container">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Students">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Student" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="surname" type="xs:string" />
                                        <xs:element name="specialty">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="ПОИТ"/>
                                                    <xs:enumeration value="ИСИТ"/>
                                                    <xs:enumeration value="ПОИБМС"/>
                                                    <xs:enumeration value="ДЭИВИ"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="isFTimeEdu" type="xs:boolean" />
                                        <xs:element name="course" type="xs:positiveInteger" />
                                        <xs:element name="perfomance" type="xs:float" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== VadimStrapko/Java/Internet_programming_technology/laba3/files/info.xml
<?xml version="1.0" encoding="utf-8"?>
<Container xmlns="http://msiter.ru" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://msiter.ru validation.xsd">
    <Students>
        <Student>
            <surname>Сидоров</surname>
            <specialty>ПОИТ</specialty>
            <isFTimeEdu>false</isFTimeEdu>
            <course>1</course>
            <perfomance>6.7</perfomance>
        </Student>
        <Student>
            <surname>Мороз</surname>
            <specialty>ИСИТ</specialty>
            <isFTimeEdu>false</isFTimeEdu>
            <course>1</course>
            <perfomance>4.7</perfomance>
        </Student>
        <Student>
            <surname>Пушкин</surname>
            <specialty>ПОИБМС</specialty>
            <isFTimeEdu>true</isFTimeEdu>
            <course>2</course>
            <perfomance>9.9</perfomance>
        </Student>
        <Student>
            <surname>Пупкин</surname>
            <specialty>ДЭИВИ</specialty>
            <isFTimeEdu>false</isFTimeEdu>
            <course>4</course>
            <perfomance>4.1</perfomance>
        </Student>
    </Students>
</Container>
